# Default port for MQTT connections
listener 1883 0.0.0.0

# Enable connections without user and password
allow_anonymous true

# Enable persistence of messages
persistence true
persistence_location /mosquitto/data/

# Where to save the logs
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout